# Generated by Django 5.2.17 on 2026-08-07 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email'], 'verbose_name': 'Vikesh', 'verbose_name_plural': 'Vikesh'},
        ),
    ]
