# Generated by Django 5.2.17 on 2026-08-07 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='vikesh_users',
        ),
    ]
